// AUTO-GENERATED by build.py — do not edit. Run build.py to regenerate.
var BLOG_DATA = {
  "example-post": {
    "title": "Example Post Title",
    "date": "October 2026",
    "preview": "The first few words of the post go here, giving readers a taste of what it covers...",
    "content": "This is an example blog post written in **Markdown**. You can use all the usual formatting.\n\n## Subheadings work\n\nSo do lists:\n\n- First item\n- Second item\n- Third item\n\n### Code blocks\n\n```python\ndef hello():\n    print(\"Hello, world!\")\n```\n\nInline code works too: `const x = 42`.\n\n### Math with LaTeX\n\nInline math: $E = mc^2$\n\nDisplay math:\n\n$$\n\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}\n$$\n\n### Images\n\nDrop images in your post by referencing them:\n\n![Screenshot](content/gallery/example-project/01.png)\n\n### Videos\n\nEmbed a YouTube video with plain HTML inside your markdown:\n\n<iframe width=\"100%\" height=\"360\" src=\"https://www.youtube.com/embed/dQw4w9WgXcQ\" frameborder=\"0\" allowfullscreen></iframe>\n\nOr a local video:\n\n<video controls width=\"100%\">\n  <source src=\"content/gallery/example-project/demo.mp4\" type=\"video/mp4\">\n</video>\n\n### Links\n\nHere is [a link to something](https://example.com) inline in text.\n\n> Blockquotes look like this.\n\nThat's it. Just write markdown."
  },
  "another-post": {
    "title": "Another Post",
    "date": "September 2026",
    "preview": "A shorter post to show that not everything needs to be long...",
    "content": "A shorter post to show that not everything needs to be long.\n\nThe quadratic formula is $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$.\n\nSimple as that."
  }
};
