import json
import os
import re

CONTENT_DIR = "content"
JS_DIR = "js"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".avif"}
GENERATED_HEADER = "// AUTO-GENERATED by build.py — do not edit. Run build.py to regenerate.\n"


def build_site_data():
    path = os.path.join(CONTENT_DIR, "site.json")
    with open(path, "r", encoding="utf-8") as f:
        site = json.load(f)

    js = GENERATED_HEADER + "var SITE_DATA = " + json.dumps(site, indent=2, ensure_ascii=False) + ";\n"

    with open(os.path.join(JS_DIR, "site-data.js"), "w", encoding="utf-8") as f:
        f.write(js)

    print("  site-data.js")


def parse_frontmatter(text):
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", text, re.DOTALL)
    if not match:
        return {}, text

    meta = {}
    for line in match.group(1).strip().split("\n"):
        colon = line.find(":")
        if colon != -1:
            key = line[:colon].strip()
            val = line[colon + 1:].strip()
            meta[key] = val

    return meta, match.group(2)


def build_blog_data():
    posts_dir = os.path.join(CONTENT_DIR, "posts")
    posts = {}

    if not os.path.isdir(posts_dir):
        os.makedirs(posts_dir)

    filenames = [f for f in os.listdir(posts_dir) if f.endswith(".md")]
    filenames.sort(reverse=True)

    for filename in filenames:
        slug = filename[:-3]
        filepath = os.path.join(posts_dir, filename)

        with open(filepath, "r", encoding="utf-8") as f:
            text = f.read()

        meta, content = parse_frontmatter(text)

        posts[slug] = {
            "title": meta.get("title", slug.replace("-", " ").replace("_", " ").title()),
            "date": meta.get("date", ""),
            "preview": meta.get("preview", ""),
            "content": content.strip(),
        }

    js = GENERATED_HEADER + "var BLOG_DATA = " + json.dumps(posts, indent=2, ensure_ascii=False) + ";\n"

    with open(os.path.join(JS_DIR, "blog-data.js"), "w", encoding="utf-8") as f:
        f.write(js)

    print(f"  blog-data.js  ({len(posts)} posts)")


def build_gallery_data():
    gallery_dir = os.path.join(CONTENT_DIR, "gallery")
    galleries = {}

    if not os.path.isdir(gallery_dir):
        os.makedirs(gallery_dir)

    for slug in sorted(os.listdir(gallery_dir)):
        slug_dir = os.path.join(gallery_dir, slug)
        if not os.path.isdir(slug_dir):
            continue

        images = []
        for fname in sorted(os.listdir(slug_dir)):
            ext = os.path.splitext(fname)[1].lower()
            if ext in IMAGE_EXTS:
                images.append("content/gallery/" + slug + "/" + fname)

        if images:
            title = slug.replace("-", " ").replace("_", " ").title()
            galleries[slug] = {"title": title, "images": images}

    js = GENERATED_HEADER + "var GALLERY_DATA = " + json.dumps(galleries, indent=2, ensure_ascii=False) + ";\n"

    with open(os.path.join(JS_DIR, "gallery-data.js"), "w", encoding="utf-8") as f:
        f.write(js)

    print(f"  gallery-data.js  ({len(galleries)} galleries)")


if __name__ == "__main__":
    os.makedirs(JS_DIR, exist_ok=True)
    print("Building site...")
    build_site_data()
    build_blog_data()
    build_gallery_data()
    print("Done! Open index.html in your browser.")
